name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          activate-environment: sscha
          python-version: '3.10'

      - name: Install Python deps
        shell: bash -l {0}
        run: |
          conda create -n sscha -c conda-forge python=3.10 gfortran libblas lapack \
          openmpi openmpi-mpicc pip numpy scipy spglib=2.2 pkgconfig
          conda activate sscha
          pip install ase julia mpi4py pytest
          pip install cellconstructor 
          which python
          python -V
          python -m pip list
          pip install cellconstructor python-sscha 

      - name: Run tests with pytest
        shell: bash -l {0}
        run: |
          which python   
          python -V
          pytest -v
